### PR TITLE
Планкина - Лабораторная работа #0

### PR DESCRIPTION
**Pull request by elenaPlankina**

### CODE REVIEW

**Comment by elenaPlankina** [comment]
@SvetlanaFilicheva
@YusipovIgor

**Comment by SvetlanaFilicheva** [comment]
+1

**Comment by SvetlanaFilicheva** [comment]
+1

**Comment by YusipovIgor** [comment]
:+1:

**Comment by elenaPlankina** [comment]
@kirill-kornyakov 
review it, please

**Comment by Daniil-Osokin** [comment]
:shipit:

**Pull request merged**
