### PR TITLE
Антон Поздеев -лаб#3

### PR DESCRIPTION
**Pull request by AntonPozdeev**

### CODE REVIEW

**Comment by AntonPozdeev** [comment]
@DobrolubovaJane, @Nikita94, @fedosov-alexander, please review

**Comment by DobrolubovaJane** [comment]
:+1:

**Comment by AntonPozdeev** [comment]
@DaryaTropicheva

**Comment by DaryaTropicheva** [comment]
:+1:

**Comment by DobrolubovaJane** [comment]
👍

**Comment by fedosov-alexander** [comment]
:+1:

**Pull request merged**
